### ISSUE TITLE
Flow Banner in Spring '22 removes Save Button from Process Builder

### ISSUE THREAD

**Issue by jczpowell** [brettgil/Salesforce-Lightning-Admin-Enhancer#16]
With the new release of Spring '22, when editing an existing process builder, the save button is pushed below the bottom of the page due to a new banner that SF added pushing users to Flow.

**Comment by brettgil** [comment]
Thanks @jczpowell I have put a fix in for this. v0.3.4  If you don't already see the update in your extensions - click update in chrome.

**Comment by jczpowell** [comment]
Fantastic, thank you for the quick turn around on the fix!
