### ISSUE TITLE
Cannot copy this text

### ISSUE THREAD

**Issue by phillipsouthern** [brettgil/Salesforce-Lightning-Admin-Enhancer#3]
When trying to copy text from an active process filter value, upon pasting I get "Cannot copy this text"

![image](https://user-images.githubusercontent.com/401021/74967661-6f6a2700-53e7-11ea-8949-4c735ca23094.png)

Pasting in vs code:

![image](https://user-images.githubusercontent.com/401021/74967702-8741ab00-53e7-11ea-96ff-0ddee999a794.png)

**Comment by brettgil** [comment]
Use aura lightning web component dev guide to understand how aura renders:  https://developer.salesforce.com/docs/component-library/documentation/en/lwc

**Comment by brettgil** [comment]
Won't fix due to process builder deprecation
